Eswe 765 setup the gradle framework
ministryofjustice/hmpps-candidate-matching-api pull request #4
Opened 2024-02-20 10:00 UTC by sacintha

2024-02-29 09:31 UTC, theDustRoom requested changes
We still have a reference to CIAG that needs to be changed

2024-02-29 09:31 UTC, theDustRoom commented on src/main/resources/migration/V1_1__start.sql
> +drop table IF EXISTS ciag_profile CASCADE;
We have reference to CIAG here

2024-02-29 13:40 UTC, sacintha commented on src/main/resources/migration/V1_1__start.sql
> +drop table IF EXISTS ciag_profile CASCADE;
Fixed

2024-03-11 11:14 UTC, theDustRoom commented on src/main/resources/migration/V1_1__start.sql
> +drop table IF EXISTS ciag_profile CASCADE;
Thanks Sacintha

2024-03-11 11:15 UTC, theDustRoom approved these changes
Builds and tests ok

2024-03-11 11:27 UTC, theDustRoom approved these changes
Builds and tests ok

2024-03-11 11:27 UTC, merged